delete from country;
INSERT INTO COUNTRY (COUNTRY_NAME, COUNTRY_CODE, MAX_MOBILE_LENGTH, COUNTRY_SHORT_CODE)
 VALUES
 ('Australia','+61', 9,'au'),
 ('Canada','+1', 10,'ca'),
 ('India','+91', 10,'in'),
 ('Singapore','+65', 8,'sg'),
 ('United Kingdom','+44', 10,'gb'),
 ('United States','+1', 10,'us');

-- following inserts are NOT to be run in test and prod environments
-- these will be used for unit testing purpose only
ALTER TABLE users DISABLE TRIGGER ALL;

-- password = 123456
insert into users (id, email, password, first_name, last_name, mobile, company_id, role, country_id, created_on, status)
values(1, 'test@litmusblox.io', '$2a$10$BwQoXoB2b9A9XE8Xc2KQbOdTGWVXYQ3QiiklqZBi/nYSRzvCPfJo.', 'Lb', 'Test', '9090909090', 2, 'Recruiter', 3, current_date, 'Active');

insert into company (id, company_name, created_on, created_by, country_id)
values(2, 'LB', current_date, 1, (select id from country where country_name = 'India'));

ALTER TABLE users ENABLE TRIGGER ALL;
-- end of inserts only for unit tests


delete from master_data;
INSERT INTO MASTER_DATA (TYPE, VALUE)
VALUES
 ('education', 'Association of Chartered Certifed Accountants (ACCA)'),
 ('education', 'Bachelor of Arts (BA)'),
 ('education', 'Bachelors of Ayurveda Medicine & Surgery (BAMS)'),
 ('education', 'Bachelor of Architecture (BArch)'),
 ('education', 'Bachelor of Business Administration (BBA)'),
 ('education', 'Bachelor of Business Management (BBM)'),
 ('education', 'Bachelors of Business Studies (BBS)'),
 ('education', 'Bachelor of Computer Applications (BCA)'),
 ('education', 'Bachelor of Commerce in Computer Application (BCCA)'),
 ('education', 'Business Capacity Management (BCM)'),
 ('education', 'Bachelor of Commerce (BCom)'),
 ('education', 'Bachelor of Computer Science (BCS)'),
 ('education', 'Bachelor of Design (BDes)'),
 ('education', 'Bachelor of Dental Science (BDS)'),
 ('education', 'Bachelor of Engineering (BE)'),
 ('education', 'Bachelor of Education (BEd)'),
 ('education', 'Bachelor in Fine Arts (BFA)'),
 ('education', 'Bachelor in Foreign Trade (BFT)'),
 ('education', 'Bachelor of Hotel Management (BHM)'),
 ('education', 'Bachelor of Homeopathic Medicine and Surgery (BHMS)'),
 ('education', 'Bachelor of Information Technology (BIT)'),
 ('education', 'Bachelor of Marketing Management (BMM)'),
 ('education', 'Bachelor in Management Studies (BMS)'),
 ('education', 'Bachelor of Pharmacy (BPharma)'),
 ('education', 'Bachelor of Law (LLB)'),
 ('education', 'Bachelor in Medicine and Bachelor of Surgery (MBBS)'),
 ('education', 'Bachelor of Science (BSc)'),
 ('education', 'Bachelor of  Science in Software Engineering (BSSE)'),
 ('education', 'Bachelor of Technology. (BTech)'),
 ('education', 'Bachelor of Veterinary Science (BVSc)'),
 ('education', 'Chartered Accountant (CA)'),
 ('education', 'Chartered Aaccountant Integrated Professional Competence Course (CA IPCC)'),
 ('education', 'Chartered Financial Accountant  (CFA)'),
 ('education', 'Commercial Art(Commercial Art)'),
 ('education', 'Company Secretary (CS)'),
 ('education', 'Cost and Works Accountancy (CWA)'),
 ('education', 'Diploma (Diploma)'),
 ('education', 'Diploma in Graphics & Animation (Diploma in Graphics & Animation)'),
 ('education', 'Doctor Of Philosophy (PhD)' ),
 ('education', 'Executive Post Graduate Diploma in Business Management (EMBA)'),
 ('education', 'Fashion/Designing (Fashion/Designing)'),
 ('education', 'Fellow of Chartered Accountants (FCA)'),
 ('education', 'Graduate Diploma in Arts (GD Arts)'),
 ('education', 'Graduate Diploma in Business Administration (GDBA)'),
 ('education', 'Higher Secondary School Certificate (HSC)'),
 ('education', 'Integrated PG Course (I PG Course)'),
 ('education', 'Institute of Cost Accountants of India - Cost and Management Accountant (ICAI CMA)'),
 ('education', 'Institute of Cost and Works Accountant of India (ICWA)'),
 ('education', 'Journalism/Mass Comunication (Journalism/Mass Comm.)'),
 ('education', 'Masters in Information Management (MIM)'),
 ('education', 'Master of Law (LLM)'),
 ('education', 'Master of Arts (MA)'),
 ('education', 'Master of Architecture (MArch)'),
 ('education', 'Master of Business Administration (MBA)'),
 ('education', 'Master of Business Management (MBM)'),
 ('education', 'Master of Computer Applications (MCA)'),
 ('education', 'Master of Computer Management (MCM)'),
 ('education', 'Master of Commerce (MCom)'),
 ('education', 'Masters in Diploma in Business Administration (MDBA)'),
 ('education', 'Management Development Programmes (MDP)'),
 ('education', 'Masters of Engineering (ME)'),
 ('education', 'Master of Education (MEd)'),
 ('education', 'Mechanical, Electrical and Plumbing (MEP)'),
 ('education', 'Masters in Fine Arts (MFA)'),
 ('education', 'Masters of finance and control (MFC)'),
 ('education', 'Master of Financial Management (MFM)'),
 ('education', 'Masters in Management Studies (MMS)'),
 ('education', 'Master of Pharmacy (MPharma)'),
 ('education', 'Masters of Philosophy (MPhil)'),
 ('education', 'Master of Personnel Management (MPM)'),
 ('education', 'Masters of Science (MS)'),
 ('education', 'Master of Science in Computer Science (MS CS)'),
 ('education', 'Master of Computer Science (MCS)'),
 ('education', 'Masters in Industrial Psychology (MS in Industrial Psychology)'),
 ('education', 'Masters of Surgery / Doctor of Medicine (MS/MD)'),
 ('education', 'Master of Science (MSc)'),
 ('education', 'Master of Social Work (MSW)'),
 ('education', 'Master of Technology (MTech)'),
 ('education', 'Master of Veterinary Science (MVSc)'),
 ('education', 'Post Graduate Diploma (PG Diploma)'),
 ('education', 'Post Graduate Certification in Business Management (PGCBM)'),
 ('education', 'Postgraduate Certificate in Human Resource Management (PGCHRM)'),
 ('education', 'Post Graduate Diploma in Analytical Chemistry (PGDAC)'),
 ('education', 'Post Graduate Diploma in Business Administration (PGDBA)'),
 ('education', 'Post Graduate Diploma in Computer Application (PGDCA)'),
 ('education', 'Post Graduate Degree in Management (PGDM)'),
 ('education', 'Post Graduate Programme in Management (PGM)'),
 ('education', 'Post Graduate Program (PGP)'),
 ('education', 'Post Graduate Programme in Business Management (PGPBM)'),
 ('education', 'Public Relations / Advertising (PR/Advertising)'),
 ('education', 'Tourism (Tourism)'),
 ('education', 'Vocational-Training (Vocational Training)'),
 ('education', 'Other (Other)'),

 ( 'addressType','Job Location'),
 ( 'addressType','Interview Location'),
 ( 'addressType','Both'),

 ( 'process','Hiring Manager'),
 ( 'process','Lead Recruiter'),
 ( 'process','Sourcing'),
 ( 'process','Screening'),
 ( 'process','Interview'),
 ( 'process','Offer Management'),

 ( 'noticePeriod','0'),
 ( 'noticePeriod','15'),
 ( 'noticePeriod','30'),
 ( 'noticePeriod','60'),
 ( 'noticePeriod','45'),
 ( 'noticePeriod','90'),
 ( 'noticePeriod','Others');

 INSERT INTO MASTER_DATA (TYPE, VALUE, VALUE_TO_USE) VALUES
 ( 'questionType','Checkbox', 'Multiple Choice'),
 ( 'questionType','Radio button', 'Single Choice'),
 ( 'questionType','InputBox', 'Short answer'),
 ( 'questionType','Location', 'Location'),
 ( 'questionType','Slider', 'Slider'),
 ( 'questionType','Calendar', 'Calendar');

delete from configuration_settings;
-- max limits for various parameters
insert into CONFIGURATION_SETTINGS(CONFIG_NAME, CONFIG_VALUE) values
('maxScreeningQuestionsLimit',50),
('dailyCandidateUploadPerUserLimit',500),
('dailyCandidateInviteLimit',500),
('candidatesPerFileLimit',100),
('sendEmail',1),
('sendSms',1),
('maxCvFiles',20),
('mlCall',1),
('maxCapabilities',10),
('cvRatingTimeout', 5000),
('otpExpiryMinutes', 3);


delete from skills_master;
 -- key skill master data
insert into skills_master (skill_name) values
('Core Java'),
('Advance Java'),
('J2EE'),
('Spring'),
('Hibernate'),
('Struts'),
('Swing'),
('MultiThreading'),
('Java Beans'),
('JSF'),
('JSP'),
('JDBC'),
('JMS'),
('Servlets'),
('Collections'),
('WebServices - Soap'),
('WebServices - Rest'),
('EJB'),
('Play'),
('JavaFX'),
('Netty'),
('Wicket'),
('JMX'),
('JAF'),
('JPA'),
('Ant'),
('Maven'),
('Gradle'),
('Tomcat'),
('JBoss'),
('GlassFish'),
('WebLogic'),
('TestNG'),
('Cactus'),
('EasyMock'),
('Mockito'),
('Cucumber'),
('Javascript - AngularJS'),
('Javascript - NodeJS'),
('Javascript - ExtJS'),
('Javascript - BackboneJS'),
('Javascript - DOJO'),
('Javascript - Jquery'),
('Javascript - EmberJS'),
('Javascript - ReactJS'),
('Javascript - KnockoutJS'),
('HTML'),
('HTML 5'),
('CSS'),
('Photoshop'),
('UX Designer'),
('CorelDraw'),
('Silverlight'),
('AJAX'),
('Javascript - Sails'),
('Javascript - Express'),
('Javascript - Grunt/Gulp'),
('Javascript - Brocolli'),
('Javascript - Webpack'),
('Javascript - Jasmine'),
('Javascript - Karma'),
('Javascript - Mocha'),
('.Net '),
('.Net - C#.Net'),
('.Net - VB.Net'),
('WCF'),
('WPF'),
('TFS'),
('VB'),
('MVC'),
('ADO'),
('Azure'),
('C#'),
('Sharepoint'),
('Excel'),
('TSQL'),
('SQL Server'),
('SQL Server SSRS'),
('SQL Server SSAS'),
('SQL Server SSIS'),
('TFS'),
('ASP'),
('Exchange'),
('ASP.NET Web API (2)'),
('ASP.NET MVC'),
('ASP.NET Web Forms (old school)'),
('nHibernate'),
('Entity Framework'),
('Linq2SQL'),
('ADO.NET'),
('nUnit'),
('SpecFlow'),
('MStest'),
('VC++'),
('STL'),
('Boost'),
('QT'),
('vxWidgets'),
('Loki'),
('POCO'),
('OpenCV'),
('VC'),
('Big Data - HBase'),
('Big Data - Hadoop'),
('Big Data - Hive'),
('Big Data - Spark'),
('Big Data - MapReduce'),
('Big Data - HDFS'),
('Big Data - MongoDB'),
('Oracle'),
('Oracle - BAM'),
('Oracle - Financials'),
('Oracle - Middleware'),
('Oracle - ORMB'),
('Oracle - SQL'),
('Oracle - Essbase'),
('MySQL'),
('NoSQL'),
('NoSQL - Cassandra'),
('NoSQL - MongoDB'),
('NoSQL - Berkeley DB'),
('NoSQL - Redis'),
('NoSQL - Riak'),
('NoSQL - CouchDB'),
('NoSQL - DynamoDB'),
('MySQL Stored Procedures'),
('MSSQL'),
('SQL'),
('DB2'),
('Postgresql'),
('Sybase'),
('Architecture'),
('Access'),
('SQLite'),
('Windows'),
('Linux'),
('RedHat RHEL'),
('Solaris'),
('Unix'),
('Android'),
('Mac/iOS'),
('Manual'),
('UAT'),
('Automation - Selenium'),
('Automation - Required'),
('Automation - Jasmine'),
('Automation - JUnit'),
('Automation - Protactor'),
('Automation - Silk Test'),
('Automation - Sahi Pro'),
('Automation - WebDriver'),
('Automation - SoapUI'),
('Automation - Watir'),
('Automation - Watin'),
('Automation - QTP'),
('Automation - Cucumber'),
('Automation - IBM Rational Functional Tester'),
('Automation - Appium'),
('Validation and Verification'),
('Performance - JMeter'),
('Performance - HP QC'),
('Performance - NeoLoad'),
('Performance - LoadRunner'),
('Performance - LoadUI'),
('Performance - Siege'),
('Performance - Gatling'),
('Infrastructure - SFTP'),
('Infrastructure - Vmware'),
('Infrastructure - SCCM'),
('Infrastructure - SCOM'),
('Infrastructure - Websence'),
('Infrastructure - Active Directory'),
('Infrastructure - Xendesktop'),
('Infrastructure - Netscalar'),
('Infrastructure - DNS'),
('Infrastructure - Web DMZ'),
('Infrastructure - ITIL'),
('Infrastructure - Application Packaging'),
('Application - JSB'),
('Application - Siebel'),
('Production'),
('Reporting - Regulatory Reporting'),
('Financial Planning and Analysis'),
('Trade Finance - Collateral Management'),
('Trade Finance'),
('Trade Finance - Settlement'),
('Risk - Market Risk'),
('Risk - Credit Risk'),
('CA'),
('Accounting'),
('PMO'),
('Fund Acounting'),
('Fund Acounting'),
('Internal Audit'),
('Finance Audit'),
('IT Audit'),
('NGO Audit'),
('HR'),
('ETL'),
('Informatica'),
('Pentaho'),
('Cognos'),
('Abinitio'),
('Business Objects'),
('Chef'),
('Puppet'),
('SVN'),
('Ansible'),
('Jenkins'),
('Artifactory'),
('Integration - Continuous'),
('Integration - Tools'),
('Nexus'),
('KVM'),
('Xen'),
('Xen'),
('VirtualBox'),
('Vagrant'),
('CFEngine'),
('SaltStack'),
('RANCID'),
('Ubuntu Juju'),
('RANCID'),
('New Relic'),
('Nagios'),
('Icinga'),
('Graphite'),
('Ganglia'),
('Cacti'),
('PagerDuty'),
('Sensu'),
('TCP/IP'),
('HTTP'),
('HTTP/2'),
('WebSockets'),
('Web Servers - Apache'),
('Web Servers - Tomcat'),
('Web Servers - IIS'),
('Web Servers - jBoss'),
('Scrum Master'),
('PMO'),
('PM'),
('Technical'),
('Business Analysis'),
('Perl'),
('Shell'),
('Python'),
('Ruby'),
('Bash'),
('AWK'),
('Python'),
('Ruby'),
('Lua'),
('Sinatra'),
('Padrino'),
('JRuby'),
('RSpec'),
('Capybara'),
('Watir'),
('Cucumber'),
('Passenger'),
('Capistrano'),
('Cake PHP'),
('Lucene'),
('Codeignitor'),
('Wordpress'),
('Joomla'),
('Symfony (2)'),
('Zend Framework (2)'),
('Yii'),
('Laravel'),
('Twig (templating)'),
('PHPUnit (testing)'),
('Doctrine (ORM)'),
('PHPStorm (IDE)'),
('Pear'),
('Smarty'),
('FICO'),
('ABAP'),
('HANA'),
('ME/MII'),
('Security'),
('MM'),
('SAP - Basis'),
('SAP - SCM'),
('GIT'),
('Subversion'),
('Endevor'),
('Mercurial'),
('SVN'),
('CVS'),
('Perforce'),
('Bitbucket'),
('Gitlab'),
('Goldensource'),
('Illustrator'),
('Flex'),
('CS'),
('Jasper/iReport'),
('Jira'),
('Pega'),
('TIBCO'),
('Tivoli'),
('Tableau'),
('TeamCity'),
('Murex'),
('Apache Kafka'),
('Memcached'),
('Nginx'),
('Varnish'),
('Squid'),
('haproxy'),
('CDN'),
('Big Data - Pig'),
('Big Data - Apache HBase'),
('Big Data - Cassandra'),
('Big Data - MapReduce'),
('Big Data - Spark'),
('TFS'),
('CruiseControl'),
('Bamboo'),
('Hudson'),
('Travis'),
('Mantis'),
('Confluence'),
('RedMine'),
('YouTrack'),
('Trello'),
('BaseCamp'),
('Visual Studio'),
('Eclipse'),
('NetBeans'),
('Aptana'),
('xCode'),
('WebStorm'),
('IntelliJ IDEA'),
('LAMP'),
('MVC'),
('OOPs'),
('SaaS'),
('Text NLP'),
('Ruby On Rails'),
('Swift'),
('XML'),
('JSON'),
('Scala'),
('Erlang'),
('OCaml'),
('Haskell'),
('F#'),
('Clojure'),
('Elixir'),
('Joomla'),
('Drupal'),
('Wordpress'),
('Magento (for e-commerce)'),
('Django'),
('Flask'),
('Pyramid'),
('Pylons'),
('SQLAlchemy'),
('web2py'),
('Kivy'),
('Akka'),
('Cats'),
('Lift'),
('Play'),
('Scalaz'),
('Slick'),
('Shapeless'),
('Spray'),
('iOS - Objective C'),
('iOS - Swift'),
('iOS - CoreData'),
('iOS - Cocoa'),
('iOS - Cocoa Touch'),
('iOS - UIKit'),
('iOS - CoreLocation'),
('iOS - CoreFoundation'),
('iOS - CoreImage'),
('iOS - CoreGraphics'),
('iOS - Cocoa Pods'),
('iOS - Flurry'),
('iOS - TestFlight'),
('iOS - HockeyApp'),
('Android - SDK'),
('Android - NDK'),
('Android - IDE'),
('Android - Gradle'),
('Android - AndEngine'),
('Android - Robotium'),
('jQuery Mobile'),
('PhoneGap'),
('Sencha Touch'),
('Dojo Mobile'),
('Titanium'),
('Xamarin'),
('OOD'),
('Design Patterns'),
('MVC'),
('SOA'),
('UML'),
('Webservices'),
('Markup'),
('Markup - XML'),
('Markup - XSLT'),
('Markup - xPath'),
('Markup - XMPP'),
('API'),
('API - Facebook API'),
('API - Google API'),
('API - Twitter API'),
('Agile'),
('Accounts Payable'),
('Asset Management'),
('Automation - Appium'),
('Business Intelligence'),
('Bootstrap'),
('C++'),
('C'),
('Chatbot'),
('CICS'),
('Citrix'),
('Claims'),
('Cloud Computing'),
('COBOL'),
('Data Analysis'),
('Data Mining'),
('Data Modelling'),
('Data Science'),
('Digital'),
('ERP/CRM'),
('Firewall'),
('Firewall'),
('Forecasting'),
('Fund Management'),
('GoldenGate'),
('Grails'),
('Hyperion'),
('Indirect Taxation'),
('Internet Protocol'),
('Marketing'),
('Digital'),
('Marketing-Head'),
('Maximo'),
('MDM'),
('Microservices'),
('MicrosoftExchange'),
('MongoDB'),
('NAT'),
('Neoload'),
('Neoload'),
('Security'),
('Networking'),
('OBIEE'),
('OFSAA'),
('OIPA'),
('OMNI'),
('Oozie'),
('OracleFusion'),
('ORMB'),
('Peoplesoft'),
('PHP'),
('QTP'),
('Recruitment'),
('Regulatory Reporting'),
('Requirement Gathering'),
('Risk'),
('Robotic Procees Automation'),
('Sailpoint'),
('Salesforce'),
('SAN'),
('SAP'),
('SAP - ICM'),
('SAP - R3'),
('SAS'),
('SCCM'),
('Big Data - Sqoop'),
('Big Data - Sqoop'),
('ServiceDesk'),
('ServiceNow'),
('Statutory Audit'),
('Tally'),
('Technical Writer'),
('UI Designer'),
('VPN'),
('Web Servers - WebLogic'),
('WindowsFAX'),
('FreeSwitch');

delete from sms_templates;
INSERT INTO SMS_TEMPLATES (TEMPLATE_NAME, TEMPLATE_CONTENT) VALUES
('ChatInvite','NEW JOB ALERT - [[${commBean.receiverfirstname}]], your profile is shortlisted by [[${commBean.sendercompany}]] for [[${commBean.jobtitle}]]. Click [[${commBean.chatlink}]] to see JD and apply.'),
('ChatCompleted','Congratulations [[${commBean.receiverfirstname}]]! Your application is complete for the [[${commBean.jobtitle}]] position at [[${commBean.sendercompany}]]. We will be in touch with you soon.'),
('ChatIncompleteReminder1','Your application to [[${commBean.sendercompany}]] was incomplete. Just click the [[${commBean.chatlink}]] to continue and complete.'),
('ChatIncompleteReminder2','FINAL REMINDER - Complete your application for [[${commBean.jobtitle}]] job at [[${commBean.sendercompany}]]. It will take only 5 minutes. Click [[${commBean.chatlink}]] to continue.'),
('LinkNotVisitedReminder1','[[${commBean.receiverfirstname}]], [[${commBean.sendercompany}]] has shortlisted you for [[${commBean.jobtitle}]] Job. Click [[${commBean.chatlink}]] to know more and apply.'),
('LinkNotVisitedReminder2','Not interested in this job? [[${commBean.sendercompany}]] has invited you to apply for the [[${commBean.jobtitle}]] position. Click [[${commBean.chatlink}]] to start.'),
('ChatNotVisitedReminder1','[[${commBean.receiverfirstname}]], this is link to apply for [[${commBean.jobtitle}]] job at [[${commBean.sendercompany}]]. It is valid only for 24 hours. Click [[${commBean.chatlink}]] to begin.'),
('ChatNotVisitedReminder2','[[${commBean.receiverfirstname}]], Just a reminder to complete your application for [[${commBean.jobtitle}]] job at [[${commBean.sendercompany}]]. This link will expire in 24 hours. [[${commBean.chatlink}]] '),
('AutosourceAcknowledgement', 'Hi [[${commBean.receiverfirstname}]], Your application for [[${commBean.jobtitle}]] position at [[${commBean.sendercompany}]] has been received. Good luck!'),
('AutosourceApplicationShortlisted', '[[${commBean.receiverfirstname}]], [[${commBean.sendercompany}]] has shortlisted you for [[${commBean.jobtitle}]] position. Click on link to complete your profile. [[${commBean.chatlink}]] '),
('AutosourceLinkNotVisited', 'Last Reminder [[${commBean.receiverfirstname}]] - [[${commBean.sendercompany}]] has shortlisted your application. Click link to complete your profile. [[${commBean.chatlink}]]'),
('OTPSms','Your OTP for [[${commBean.sendercompany}]] job application is [[${commBean.otp}]]. This OTP will expire in [[${commBean.otpExpiry}]] minutes.'),
('InterviewDay', 'INTERVIEW REMINDER FOR [[${commBean.receiverfirstname}]] - You have an interview with [[${commBean.sendercompany}]] today at [[${commBean.interviewdate}]]. Please report 15 mins before. Click Google Maps link for directions. See you there! [[${commBean.interviewAddressLink}]]');

delete from create_job_page_sequence;
INSERT INTO CREATE_JOB_PAGE_SEQUENCE (PAGE_DISPLAY_NAME, PAGE_NAME, PAGE_DISPLAY_ORDER, DISPLAY_FLAG,SUBSCRIPTION_AVAILABILITY)
VALUES
('Overview', 'overview', 1, 'T','Lite'),
('Expertise', 'expertise', 3, 'F','Lite'),
('Job Detail', 'jobDetail', 8, 'F','Max'),
('Screening', 'screeningQuestions', 2, 'T','Lite'),
('Key Skills', 'keySkills', 4, 'T','Lite'),
('Hiring Team', 'hiringTeam', 6, 'T','Max'),
('Capabilities', 'capabilities', 5, 'T','Lite'),
('Preview', 'preview', 7, 'T','Lite');

INSERT INTO MASTER_DATA (TYPE, VALUE, VALUE_TO_USE, COMMENTS)
VALUES
 ( 'expertise','Fresher', 1, 'Candidate has 1-2 years of relevant work experience and works on given tasks on day to day basis. Exposure to job complexities is limited and needs support/guidance for complex tasks.'),
 ( 'expertise','Junior', 2, null),
 ( 'expertise','Mid', 3, 'Candidate can independently handle all tasks. Typically has 2 - 5 years of relevant work experience. Dependable on senior for assigned work. Can participate in training/grooming of juniors'),
 ( 'expertise','Senior', 4, 'Considered as a Master in the organization/industry. Candidate can handle highly complex scenarios and is the go-to person for others. Such candidates are rare to find and often come at a high cost. Select this option if you want to hire a expert.'),
 ( 'expertise','Top Management', 5, null);

INSERT INTO MASTER_DATA (TYPE, VALUE)
VALUES
( 'experienceRange', '0 - 2 Years'),
( 'experienceRange', '2 - 4 Years'),
( 'experienceRange', '4 - 6 Years'),
( 'experienceRange', '6 - 8 Years'),
( 'experienceRange', '8 - 10 Years'),
( 'experienceRange', '10 - 15 Years'),
( 'experienceRange', '15 - 20 Years'),
( 'experienceRange', '20+ Years'),

( 'oldFunction','Accounting / Tax / Company Secretary / Audit'),
( 'oldFunction','Agent'),
( 'oldFunction','Airline / Reservations / Ticketing / Travel'),
( 'oldFunction','Analytics & Business Intelligence'),
( 'oldFunction','Anchoring / TV / Films / Production'),
( 'oldFunction','Architects / Interior Design / Naval Arch');

delete from weightage_cutoff_mapping;
insert into weightage_cutoff_mapping (weightage, percentage, cutoff, star_rating)
values
(2,100,10,1),
(2,100,20,2),
(2,80,40,3),
(2,40,80,4),
(2,20,100,5),
(6,100,20,1),
(6,100,40,2),
(6,60,60,3),
(6,20,100,4),
(6,0,100,5),
(10,0,30,1),
(10,0,50,2),
(10,0,70,3),
(10,0,80,4),
(10,0,100,5);

INSERT INTO public.currency(currency_full_name, currency_short_name, country, min_salary, max_salary, salary_unit) VALUES
('Australian Dollar', 'AUD', 'au', 30, 250, 'K'),
('Canadian Dollar', 'CAD', 'ca', 30, 250, 'K'),
('Indian Rupee', 'INR', 'in', 1, 100, 'L'),
('Singapore Dollar', 'SGD', 'sg', 30, 250, 'K'),
('Pound Sterling', 'GBP', 'gb', 30, 250, 'K'),
('US Dollar', 'USD', 'us', 30, 250, 'K');

Insert into STAGE_STEP_MASTER(STAGE, STEP)
VALUES ('Sourcing','Sourcing'),
('Screening','Screening'),
('Submitted','Submitted'),
('Interview','L1'),
('Make Offer','Make Offer'),
('Offer','Offer'),
('Hired','Hired');

INSERT INTO public.master_data(type, value, value_to_use) VALUES
('userRole', 'HR Recruiter', 'Recruiter'),
('userRole', 'HR Head', 'ClientAdmin'),
('userRole', 'Admin', 'ClientAdmin'),
('userRole', 'Hiring Manager', 'BusinessUser'),
('userRole', 'Interviewer', 'BusinessUser');

--Ticket #258
INSERT INTO export_format_master
(format, system_supported)
values
('All Data', true);

INSERT INTO export_format_detail
(format_id, column_name, header,  "position", stage)
VALUES
(1, 'candidateName','Candidate Name', 1, null),
(1, 'chatbotStatus','Chatbot Status', 2, null),
(1, 'chatbotFilledTimeStamp', 'Chatbot Filled Timestamp', 3, null),
(1, 'currentStage','Stage', 4, null),
(1, 'keySkillsStrength','Key Skills Strength', 5, null),
(1, 'currentCompany','Current Company', 6, null),
(1, 'currentDesignation','Current Designation', 7, null),
(1, 'email','Email', 8, null),
(1, 'countryCode','Country Code', 9, null),
(1, 'mobile','Mobile', 10, null),
(1, 'totalExperience','Total Experience', 11, null),
(1, 'createdBy','Created By', 12, null),
(1, 'interviewDate','Interview Date', 13, 'Interview'),
(1, 'interviewType','Interview Type', 14, 'Interview'),
(1, 'interviewMode','Interview Mode', 15, 'Interview'),
(1, 'interviewLocation','Interview location', 16, 'Interview'),
(1, 'candidateConfirmation','Candidate Confirmation', 17, 'Interview'),
(1, 'candidateConfirmationTime','Candidate Confirmation Time', 18, 'Interview'),
(1, 'showNoShow','Show No Show', 19, 'Interview'),
(1, 'noShowReason','No Show Reason' ,20, 'Interview'),
(1, 'cancelled', 'Interview Cancelled', 21, 'Interview'),
(1, 'cancellationReason','Cancellation Reason', 22, 'Interview');

Insert into MASTER_DATA (TYPE, VALUE) values
('reasonForChange','Too much time spent in Commuting to work'),
('reasonForChange','Too much travelling in the job'),
('reasonForChange','Have been in same company for too long'),
('reasonForChange','Company has shutdown'),
('reasonForChange','Company is downsizing /got a layoff'),
('reasonForChange','Am a Contract employee, want to shift to permanent employment'),
('reasonForChange','Want to work in a different domain'),
('reasonForChange','Want to work in a different project'),
('reasonForChange','Not getting paid my salary on time'),
('reasonForChange','Have not been promoted for a long time'),
('reasonForChange','Want to work with a Larger Size Company'),
('reasonForChange','Want to work with a Bigger Brand'),
('reasonForChange','Want to get away from shift working'),
('reasonForChange','Have been on maternity break'),
('reasonForChange','Have been on Sabbatical'),
('reasonForChange','Other');

INSERT INTO MASTER_DATA(TYPE, VALUE) VALUES
('callOutCome', 'Connected'),
('callOutCome', 'No Answer'),
('callOutCome', 'Busy'),
('callOutCome', 'Wrong Number'),
('callOutCome', 'Left Message/VoiceMail');

Insert into MASTER_DATA (TYPE, VALUE) values
('cancellationReasons','Client cancelled iv 1'),
('cancellationReasons','Candidate no show 1'),
('cancellationReasons','Panel not available 1'),
('cancellationReasons','Client cancelled iv 2'),
('cancellationReasons','Candidate no show 2'),
('cancellationReasons','Panel not available 2'),

('noShowReasons','Personal/Family'),
('noShowReasons','Professional'),
('noShowReasons','Medical'),
('noShowReasons','Logistics'),
('noShowReasons','Not reachable'),
('noShowReasons','Client Cancellation');

INSERT INTO CV_PARSING_API_DETAILS (API_URL, API_SEQUENCE, ACTIVE, COLUMN_TO_UPDATE, QUERY_ATTRIBUTES) VALUES
('https://rest.rchilli.com/RChilliParser/Rchilli/parseResume', 1, false, 'PARSING_RESPONSE_JSON',
'"userkey" => "2SNEDYNPV30",
"version" => "7.0.0",
"subuserid" => "Hexagon Search"'
),
('http://cvparser.litmusblox.net/parsecv', 2, true, 'PARSING_RESPONSE_PYTHON',null
),
('https://cia1z4r0d4.execute-api.ap-south-1.amazonaws.com/Test/resumeParser-Test', 3, true, 'PARSING_RESPONSE_ML',
null
);

INSERT INTO REJECTION_REASON_MASTER_DATA (VALUE, LABEL, TYPE, STAGE) VALUES
('Company', '','Candidate Reasons', 1),
('Shift', 'Candidate does not want to work in shifts','Candidate Reasons', 1),
('Commute', 'Candidate not willing to commute','Candidate Reasons', 1),
('IC Role', 'Candidate not willing to work in Individual Contributor (IC) role','Candidate Reasons', 1),
('People Role', 'Candidate not willing to work in People Management role','Candidate Reasons', 1),

('Company', '','Candidate Reasons', 2),
('Shift', 'Candidate does not want to work in shifts','Candidate Reasons', 2),
('Commute', 'Candidate not willing to commute','Candidate Reasons', 2),
('IC Role', 'Candidate not willing to work in Individual Contributor (IC) role','Candidate Reasons', 2),
('People Role', 'Candidate not willing to work in People Management role','Candidate Reasons', 2),

('Job Hops', 'Candidate has many job changes','Recruiter Reasons', 1),
('Over Budget', 'Candidates salary expectation is higher than budget','Recruiter Reasons', 1),
('No Poach', 'Candidate works in No Poach company','Recruiter Reasons', 1),
('Skill Missing', 'Candidate is missing required skills','Recruiter Reasons', 1),
('Already interviewed', 'Candidate has given interview earlier','Recruiter Reasons', 1),
('Over-Qualified', 'Candidate has more experience than required','Recruiter Reasons', 1),
('Under-Qualified', 'Candidate has less experience than required','Recruiter Reasons', 1),
('Education', 'Candidate does not have the correct education qualifications','Recruiter Reasons', 1),
('Communication', 'Candidate does not have adequate communication skills','Recruiter Reasons', 1),
('Notice Period', 'Candidates Notice Period is too long','Recruiter Reasons', 1),
('Not Available', 'Candidate not available for interview on a specific date','Recruiter Reasons', 1),
('Not interested', 'Candidate not interested in this job','Recruiter Reasons', 1),
('Not looking', 'Candidate is not looking for a job change','Recruiter Reasons', 1),
('Key Skill Strength', 'Candidate Key Skill Strength is poor','Recruiter Reasons', 1),
('No Response', 'Candidate has not responded to chatbot invitation','Recruiter Reasons', 1),
('Chatbot Incomplete', 'Candidate has not completed the chatbot','Recruiter Reasons', 1),
('Not Interested', 'Candidate has expressed disinterest in the job','Recruiter Reasons', 1),

('Job Hops', 'Candidate has many job changes','Recruiter Reasons', 2),
('Over Budget', 'Candidates salary expectation is higher than budget','Recruiter Reasons', 2),
('No Poach', 'Candidate works in No Poach company','Recruiter Reasons', 2),
('Skill Missing', 'Candidate is missing required skills','Recruiter Reasons', 2),
('Already interviewed', 'Candidate has given interview earlier','Recruiter Reasons', 2),
('Over-Qualified', 'Candidate has more experience than required','Recruiter Reasons', 2),
('Under-Qualified', 'Candidate has less experience than required','Recruiter Reasons', 2),
('Education', 'Candidate does not have the correct education qualifications','Recruiter Reasons', 2),
('Communication', 'Candidate does not have adequate communication skills','Recruiter Reasons', 2),
('Notice Period', 'Candidates Notice Period is too long','Recruiter Reasons', 2),
('Not Available', 'Candidate not available for interview on a specific date','Recruiter Reasons', 2),
('Not interested', 'Candidate not interested in this job','Recruiter Reasons', 2),
('Not looking', 'Candidate is not looking for a job change','Recruiter Reasons', 2),
('Key Skill Strength', 'Candidate Key Skill Strength is poor','Recruiter Reasons', 2),
('No Response', 'Candidate has not responded to chatbot invitation','Recruiter Reasons', 2),
('Chatbot Incomplete', 'Candidate has not completed the chatbot','Recruiter Reasons', 2),
('Not Interested', 'Candidate has expressed disinterest in the job','Recruiter Reasons', 2),

('Skill Missing', 'Candidate is missing required skills',null, 3),
('Industry / Domain', 'Candidate is missing Industry / Domain background',null, 3),
('Already interviewed', 'Candidate has been interviewed earlier',null, 3),
('Over-Qualified', 'Candidate has more experience than required',null, 3),
('Under-Qualified', 'Candidate has less experience than required',null, 3),
('Education', 'Candidate does not have the required education qualifications',null, 3),
('Communication', 'Candidate does not have adequate communication skills',null, 3),
('Assessment', 'Candidate did not clear the assessment test',null, 3),

('Technical', 'Technical skills not adequate',null, 4),
('Managerial', 'Managerial / People skills not adequate',null, 4),
('Culture', 'Not a culture fit for the company',null, 4),
('Industry / Domain', 'Industry / Domain experience not adequate',null, 4),
('Behavioral', 'Behavioral competencies not adequate',null, 4),
('Compensation fitment', 'Not able to fit candidate in the compensation band',null, 4),
('Another Candidate', 'Another candidate selected for this job',null, 4),

('Personal/Family', 'Personal or Family emergency',null, 4),
('Professional', 'Unexpected meeting, Client visit, Production issue',null, 4),
('Medical', 'Medical Emergency, Candidate unwell',null, 4),
('Logistics', 'Weather / Accident / Vehicle problems',null, 4),
('No Response', 'Candidate has stopped responding to calls',null, 4),
('Hiring Manager', 'Hiring Manager cancelled / rescheduled the interview',null, 4),

('Position Scrapped', 'Position has been scrapped',null, 5),
('No Approval', 'No approval for position / Approval withdrawn',null, 5),
('Other Offer', 'Candidate received another offer',null, 5),
('Withdraw Candidature', 'Candidate is no longer interested in the job',null, 5),

('Role', 'Candidate did not like the Role offered',null, 6),
('Title', 'Candidate did not like the Title offered',null, 6),
('Compensation', 'Candidate did not like to Compensation offered',null, 6),
('Interview experience', 'Candidate did not like the Interview expereince',null, 6),
('Relocation', 'Candidate does not want to Relocate',null, 6),
('Counteroffer', 'Candidate accepted counter-offer from his company',null, 6),
('Onsite', 'Candidate received an onsite opportunity',null, 6),
('Other Offer', 'Candidate accepted offer from another company',null, 6),
('Withdraw Offer', 'Company withdrew the offer',null, 6),

('Performance', 'Candidate was asked to leave on Performance grounds',null, 7),
('Background Verification', 'Candidates Background Verification (BGV) report was negative',null, 7),
('Integrity', 'Candidate was asked to leave on grounds of integrity',null, 7),
('Voluntary exit', 'Candidate left on their own accord',null, 7);

INSERT INTO INDUSTRY_MASTER_DATA(INDUSTRY) VALUES
('IT'),
('Manufacturing - Products');

INSERT INTO FUNCTION_MASTER_DATA(FUNCTION, INDUSTRY) VALUES
('Testing', (select id from industry_master_data where industry = 'IT')),
('Project/ Program Management', (select id from industry_master_data where industry = 'IT')),
('SI / ERP / CRM Product Integration', (select id from industry_master_data where industry = 'IT')),
('Architecture & Design', (select id from industry_master_data where industry = 'IT')),
('UI / UX', (select id from industry_master_data where industry = 'IT')),
('Digital / Social Media Marketing', (select id from industry_master_data where industry = 'IT')),
('Pre-Sales & Proposals', (select id from industry_master_data where industry = 'IT')),
('Application / Product Support', (select id from industry_master_data where industry = 'IT')),
('Team / Module Lead', (select id from industry_master_data where industry = 'IT')),
('Business Analysis / Requirement Analysis / BPM', (select id from industry_master_data where industry = 'IT')),
('Product Management', (select id from industry_master_data where industry = 'IT')),
('System Administration', (select id from industry_master_data where industry = 'IT')),
('Global Service Desk / End User Computing', (select id from industry_master_data where industry = 'IT')),
('Database Administration', (select id from industry_master_data where industry = 'IT')),
('Network Management', (select id from industry_master_data where industry = 'IT')),
('PMO, Contracts & Governance', (select id from industry_master_data where industry = 'IT')),
('Business Development', (select id from industry_master_data where industry = 'IT')),
('Customer Care', (select id from industry_master_data where industry = 'IT')),
('HR', (select id from industry_master_data where industry = 'IT')),
('Training / L&D', (select id from industry_master_data where industry = 'IT')),
('Recruitment', (select id from industry_master_data where industry = 'IT')),
('Media & Content', (select id from industry_master_data where industry = 'IT')),
('Admin / Facility Management', (select id from industry_master_data where industry = 'IT')),
('Accounts / Finance', (select id from industry_master_data where industry = 'IT')),
('Vendor Contracts & Commercials', (select id from industry_master_data where industry = 'IT')),
('Business Analytics & MIS', (select id from industry_master_data where industry = 'IT')),
('Quality Systems / Business Excellence', (select id from industry_master_data where industry = 'IT')),
('Health & Safety', (select id from industry_master_data where industry = 'IT')),
('Corporate Social Responsibilities', (select id from industry_master_data where industry = 'IT')),
('CFO, Legal & Secreterial', (select id from industry_master_data where industry = 'IT')),
('Corporate Communication & Brand Management', (select id from industry_master_data where industry = 'IT')),
('Corporate Governance', (select id from industry_master_data where industry = 'IT')),
('Business Strategy Planning', (select id from industry_master_data where industry = 'IT')),
('Product Development / R&D', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Manufacturing / Process / Industrial Engineering', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Plant Equipment & Machinery Engineering', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Tool Engineering', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Production', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Quality', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Plant Maintenance', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Production Planning & Control', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Vendor Development / Sourcing / Purchase / Procurement', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Stores, Warehouse & Inventory Control', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Coding / Programming', (select id from industry_master_data where industry = 'IT')),
('Logistics', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Operator / Technician', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Health, Safety & Environment', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Sales - Direct', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Sales - Channel', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Marketing & Lead Generation', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Pre-Sales, Proposals & Tenders', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Customer Care', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('After Sales / Field Service', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('HR', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Training / L&D', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Recruitment', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Media & Content', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Admin / Facility Management', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Accounts / Finance', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('IT Infra management / ITES', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('IT Enterprise Systems (CIO)', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Business Analytics & MIS', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Quality Systems / Business Excellence', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Corporate Social Responsibilities', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Corporate Finance, Legal & Secreterial', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Corporate Communication & Brand Management', (select id from industry_master_data where industry = 'Manufacturing - Products')),
('Business Strategy Planning', (select id from industry_master_data where industry = 'Manufacturing - Products'));


INSERT INTO ROLE_MASTER_DATA(ROLE, FUNCTION) VALUES
('Manual Tester', (select id from function_master_data where function = 'Testing' and industry = (select id from industry_master_data where industry = 'IT'))),
('Automation Tester', (select id from function_master_data where function = 'Testing'and industry = (select id from industry_master_data where industry = 'IT'))),
('Project Manager - Testing', (select id from function_master_data where function = 'Testing'and industry = (select id from industry_master_data where industry = 'IT'))),
('Test Architect', (select id from function_master_data where function = 'Testing'and industry = (select id from industry_master_data where industry = 'IT'))),
('Testing Team Lead', (select id from function_master_data where function = 'Testing' and industry = (select id from industry_master_data where industry = 'IT'))),
('Project /Program  Manager - ADMS', (select id from function_master_data where function = 'Project/ Program Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Project / Program Manager - SI projects', (select id from function_master_data where function = 'Project/ Program Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Project / Program Manager - Product Development', (select id from function_master_data where function = 'Project/ Program Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Client Account & Delivery Manager', (select id from function_master_data where function = 'Project/ Program Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Program Management Office & Contracts', (select id from function_master_data where function = 'Project/ Program Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('SCRUM Master', (select id from function_master_data where function = 'Project/ Program Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Functional Consultant - SI /ERP/CRM integration', (select id from function_master_data where function = 'SI / ERP / CRM Product Integration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Technical Consultant - SI /ERP/CRM integration', (select id from function_master_data where function = 'SI / ERP / CRM Product Integration' and industry = (select id from industry_master_data where industry = 'IT'))),
('SI / ERP / CRM- Platform Build & Support', (select id from function_master_data where function = 'SI / ERP / CRM Product Integration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Enterprise Architect', (select id from function_master_data where function = 'Architecture & Design' and industry = (select id from industry_master_data where industry = 'IT'))),
('Technical Architect', (select id from function_master_data where function = 'Architecture & Design' and industry = (select id from industry_master_data where industry = 'IT'))),
('Infra Architect', (select id from function_master_data where function = 'Architecture & Design' and industry = (select id from industry_master_data where industry = 'IT'))),
('Product Architect', (select id from function_master_data where function = 'Architecture & Design' and industry = (select id from industry_master_data where industry = 'IT'))),
('UI Designer', (select id from function_master_data where function = 'UI / UX' and industry = (select id from industry_master_data where industry = 'IT'))),
('UI Programmer', (select id from function_master_data where function = 'UI / UX' and industry = (select id from industry_master_data where industry = 'IT'))),
('UX Designer', (select id from function_master_data where function = 'UI / UX' and industry = (select id from industry_master_data where industry = 'IT'))),
('SEO & Analytics Specialist', (select id from function_master_data where function = 'Digital / Social Media Marketing' and industry = (select id from industry_master_data where industry = 'IT'))),
('Social Media Marketing Expert', (select id from function_master_data where function = 'Digital / Social Media Marketing' and industry = (select id from industry_master_data where industry = 'IT'))),
('Content Developer / Copywriter', (select id from function_master_data where function = 'Digital / Social Media Marketing' and industry = (select id from industry_master_data where industry = 'IT'))),
('Campaign Manager', (select id from function_master_data where function = 'Digital / Social Media Marketing' and industry = (select id from industry_master_data where industry = 'IT'))),
('InBound Marketing', (select id from function_master_data where function = 'Digital / Social Media Marketing' and industry = (select id from industry_master_data where industry = 'IT'))),
('Pre Sales - Manager / Coordinator', (select id from function_master_data where function = 'Pre-Sales & Proposals' and industry = (select id from industry_master_data where industry = 'IT'))),
('Pre Sales - Solution Architect', (select id from function_master_data where function = 'Pre-Sales & Proposals' and industry = (select id from industry_master_data where industry = 'IT'))),
('L1 Support', (select id from function_master_data where function = 'Application / Product Support' and industry = (select id from industry_master_data where industry = 'IT'))),
('L2 Support', (select id from function_master_data where function = 'Application / Product Support' and industry = (select id from industry_master_data where industry = 'IT'))),
('Application Development & Maintenance', (select id from function_master_data where function = 'Application / Product Support' and industry = (select id from industry_master_data where industry = 'IT'))),
('Service Manager', (select id from function_master_data where function = 'Application / Product Support' and industry = (select id from industry_master_data where industry = 'IT'))),
('Release & Deployment Manager', (select id from function_master_data where function = 'Application / Product Support' and industry = (select id from industry_master_data where industry = 'IT'))),
('Development Team Lead', (select id from function_master_data where function = 'Team / Module Lead' and industry = (select id from industry_master_data where industry = 'IT'))),
('Testing Team Lead', (select id from function_master_data where function = 'Team / Module Lead' and industry = (select id from industry_master_data where industry = 'IT'))),
('Team Lead - Application support', (select id from function_master_data where function = 'Team / Module Lead' and industry = (select id from industry_master_data where industry = 'IT'))),
('Business Analyst', (select id from function_master_data where function = 'Business Analysis / Requirement Analysis / BPM' and industry = (select id from industry_master_data where industry = 'IT'))),
('Business Consultant', (select id from function_master_data where function = 'Business Analysis / Requirement Analysis / BPM' and industry = (select id from industry_master_data where industry = 'IT'))),
('Requirements Manager', (select id from function_master_data where function = 'Business Analysis / Requirement Analysis / BPM' and industry = (select id from industry_master_data where industry = 'IT'))),
('Bus Process Consultant', (select id from function_master_data where function = 'Business Analysis / Requirement Analysis / BPM' and industry = (select id from industry_master_data where industry = 'IT'))),
('Product Manager / Owner', (select id from function_master_data where function = 'Product Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('SCRUM Master', (select id from function_master_data where function = 'Product Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Product Module Lead', (select id from function_master_data where function = 'Product Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Product Release Manager', (select id from function_master_data where function = 'Product Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('System Admin - OS & Servers', (select id from function_master_data where function = 'System Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Storage Admin', (select id from function_master_data where function = 'System Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Backup Admin', (select id from function_master_data where function = 'System Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Cloud Infra Admin', (select id from function_master_data where function = 'System Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Mail Server Admin', (select id from function_master_data where function = 'System Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Middleware Admin', (select id from function_master_data where function = 'System Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Database Admin', (select id from function_master_data where function = 'Database Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Storage Admin', (select id from function_master_data where function = 'Database Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Backup Admin', (select id from function_master_data where function = 'Database Administration' and industry = (select id from industry_master_data where industry = 'IT'))),
('Network Administrator', (select id from function_master_data where function = 'Network Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Firewall Internet Network Security Administrator', (select id from function_master_data where function = 'Network Management' and industry = (select id from industry_master_data where industry = 'IT'))),
('Contract Scoping & Initiation', (select id from function_master_data where function = 'PMO, Contracts & Governance' and industry = (select id from industry_master_data where industry = 'IT'))),
('Contract Management & Governance', (select id from function_master_data where function = 'PMO, Contracts & Governance' and industry = (select id from industry_master_data where industry = 'IT'))),
('B2B Sales / Business Development', (select id from function_master_data where function = 'Business Development' and industry = (select id from industry_master_data where industry = 'IT'))),
('Account Manager', (select id from function_master_data where function = 'Business Development' and industry = (select id from industry_master_data where industry = 'IT'))),
('Marketing & Lead Generation', (select id from function_master_data where function = 'Business Development' and industry = (select id from industry_master_data where industry = 'IT'))),
('Customer Care Manager / Executive', (select id from function_master_data where function = 'Customer Care' and industry = (select id from industry_master_data where industry = 'IT'))),
('Global Service Desk / End User Computing', (select id from function_master_data where function = 'Global Service Desk / End User Computing' and industry = (select id from industry_master_data where industry = 'IT')));

Insert into MASTER_DATA (TYPE, VALUE) values
('questionCategory','Location'),
('questionCategory','Shifts'),
('questionCategory','Domain'),
('questionCategory','Team Size (Direct)'),
('questionCategory','Team Size (Indirect)'),
('questionCategory','Notice Period'),
('questionCategory','Contract'),
('questionCategory','Salary'),
('questionCategory','Reason for job change'),
('questionCategory','Other Offers'),
('questionCategory','Interview'),
('questionCategory','Remote Working'),
('questionCategory','Education'),
('questionCategory','Travel'),
('questionCategory','Required Docs'),
('questionCategory','Languages'),
('questionCategory','Start Date');

INSERT INTO SCREENING_QUESTION (QUESTION, QUESTION_TYPE, OPTIONS, MULTILEVELOPTIONS, QUESTION_CATEGORY, COUNTRY_ID) VALUES
('Which City are you currently based in?', (select id from master_data where value = 'Radio button'), '{"Bangalore","Chennai","Delhi NCR","Hyderabad","Pune","Mumbai","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Location'), (select id from country where country_name = 'India')),
('For a great job opportunity, which cities are you willing to relocate?', (select id from master_data where value = 'Checkbox'), null, ' {"No, I won’t relocate to another city": [],"Yes, I would relocate to": ["Bangalore","Chennai","Delhi NCR","Hyderabad","Pune","Mumbai","Other"]}', (select id from master_data where type = 'questionCategory' and value = 'Location'), (select id from country where country_name = 'India')),
('Does your current job require you to work in Shifts?', (select id from master_data where value = 'Radio button'), '{"No shifts, I work regular day timings (9:00 AM – 6:00 PM)","UK shift (12:00  PM – 9:00 PM)","US shift (6:00 PM – 4:00 AM)","APAC shift (6:00 AM – 3:00 PM)","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Shifts'), (select id from country where country_name = 'India')),
('Are you available to work in Shifts?', (select id from master_data where value = 'Checkbox'), '{"No shifts, I want to work regular day timings (9:00 AM – 6:00 PM)","Morning / APAC shift (6:00 AM – 3:00 PM)","Evening / UK shift (12:00  PM – 9:00 PM)","Night / US shift (6:00 PM – 4:00 AM)","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Shifts'), (select id from country where country_name = 'India')),
('Do you have a strong experience in any of these Industry Domains', (select id from master_data where value = 'Checkbox'), '{"Banking","Financial Services","Insurance","Telecom","Retail","Healthcare","E-Commerce","Travel & Hospitality","Media & Entertainment","Gaming","Consulting","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Domain'), (select id from country where country_name = 'India')),
('Do you lead a team of direct reports?', (select id from master_data where value = 'Radio button'), '{"I am an Individual Contributor","Small size team (1-3 people)","Medium size team (4-6 people)","Large size team (7-10 people)","Really large team (10+ people)"}', null, (select id from master_data where type = 'questionCategory' and value = 'Team Size (Direct)'), (select id from country where country_name = 'India')),
('What is your total team size including indirect reports?', (select id from master_data where value = 'Radio button'), '{<10,11-25,26-50,51-100,101-500,501-1000,1001-5000, 5000+}', null, (select id from master_data where type = 'questionCategory' and value = 'Team Size (Indirect)'), (select id from country where country_name = 'India')),
('What is the official Notice Period you are required to serve in your current company?', (select id from master_data where value = 'Radio button'), '{"I can join immediately","15 days","30 days","45 days","60 days","90 days"}', null, (select id from master_data where type = 'questionCategory' and value = 'Notice Period'), (select id from country where country_name = 'India')),
('If the need arises, can you buyout the notice period?', (select id from master_data where value = 'Radio button'), '{"Yes","No"}', null, (select id from master_data where type = 'questionCategory' and value = 'Notice Period'), (select id from country where country_name = 'India')),
('Would you be willing to work on a Contract position?', (select id from master_data where value = 'Radio button'), '{"Yes, certainly","Yes, for the right opportunity","No, I will not work on contract"}', null, (select id from master_data where type = 'questionCategory' and value = 'Contract'), (select id from country where country_name = 'India')),
('What is your Current Annual Salary?', (select id from master_data where value = 'Slider'), null, null, (select id from master_data where type = 'questionCategory' and value = 'Salary'), (select id from country where country_name = 'India')),
('What is your expected annual salary requirement?', (select id from master_data where value = 'Slider'),null, null, (select id from master_data where type = 'questionCategory' and value = 'Salary'), (select id from country where country_name = 'India')),
('What are the main reasons that you are looking for a job change?', (select id from master_data where value = 'Checkbox'), '{"Too much time spent in commuting to work","Too much travelling in the job","Have been in same company for too long","Company has shut down","Company is downsizing/got a layoff","Am a contract employee, want to shift to a permanent job","Want to work in a different domain", "Want to work in a different project", "Not getting paid my salary on time","Have not been promoted for a long time","Want to work with a larger company/brand","Want to work with a smaller company", "Want to work regular shifts","Have been on maternity break","Have been on Sabbatical","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Reason for job change'), (select id from country where country_name = 'India')),
('Do you have other offers in hand?', (select id from master_data where value = 'Radio button'), '{"No, I don’t have any other offers as of today","Yes, I have resigned and am serving my notice period"}', null, (select id from master_data where type = 'questionCategory' and value = 'Other Offers'), (select id from country where country_name = 'India')),
('Are you willing to work remotely?', (select id from master_data where value = 'Radio button'), '{"Yes","No"}', null, (select id from master_data where type = 'questionCategory' and value = 'Remote Working'), (select id from country where country_name = 'India')),
('What is your highest level of education?', (select id from master_data where value = 'Radio button'), '{"Secondary (10th Grade)","Higher Secondary (12th Grade)","Diploma","Bachelor’s","Master’s","Doctorate"}', null, (select id from master_data where type = 'questionCategory' and value = 'Education'), (select id from country where country_name = 'India')),
('This job may require outstation travel. How long are you willing to travel every month?', (select id from master_data where value = 'Radio button'), '{"I am not willing to travel","25% of the time","50% of the time","75% of the time","100% of the time"}', null, (select id from master_data where type = 'questionCategory' and value = 'Travel'), (select id from country where country_name = 'India')),
('If required, which of the following documents can you provide?', (select id from master_data where value = 'Checkbox'), '{"Address Proof","PAN Card","Aadhar Card","Passport","Driver’s Licence","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Required Docs'), (select id from country where country_name = 'India')),
('Which of these languages can you speak fluently?', (select id from master_data where value = 'Checkbox'), '{"English","Hindi","Bengali","Marathi","Telugu","Tamil","Gujarati","Urdu","Kannada","Oriya","Malayalam","Punjabi","Other"}', null, (select id from master_data where type = 'questionCategory' and value = 'Languages'), (select id from country where country_name = 'India')),
('What is the earliest start date that you can commit to?', (select id from master_data where value = 'Calendar'), null, null, (select id from master_data where type = 'questionCategory' and value = 'Start Date'), (select id from country where country_name = 'India'));

INSERT INTO CREATE_JOB_PAGE_SEQUENCE (PAGE_DISPLAY_NAME, PAGE_NAME, PAGE_DISPLAY_ORDER, DISPLAY_FLAG,SUBSCRIPTION_AVAILABILITY) VALUES
('Job Details', 'jobDetail', 1, 'T','Lite'),
('Job Screening', 'jobScreening', 2, 'T','Lite'),
('HR Screening', 'hrScreening', 3, 'T','Lite'),
('Custom Questions', 'customQuestions', 4, 'T','Lite'),
('Publish', 'publish', 5, 'T','Lite');
