delete from country;
INSERT INTO COUNTRY (COUNTRY_NAME, COUNTRY_CODE, MAX_MOBILE_LENGTH, COUNTRY_SHORT_CODE)
 VALUES
 ('Australia','+61', 9,'au'),
 ('Canada','+1', 10,'ca'),
 ('India','+91', 10,'in'),
 ('Singapore','+65', 8,'sg'),
 ('United Kingdom','+44', 10,'gb'),
 ('United States','+1', 10,'us');

-- following inserts are NOT to be run in test and prod environments
-- these will be used for unit testing purpose only
ALTER TABLE users DISABLE TRIGGER ALL;

-- password = 123456
insert into users (id, email, password, first_name, last_name, mobile, company_id, role, country_id, created_on, status)
values(1, 'test@litmusblox.io', '$2a$10$BwQoXoB2b9A9XE8Xc2KQbOdTGWVXYQ3QiiklqZBi/nYSRzvCPfJo.', 'Lb', 'Test', '9090909090', 2, 'Recruiter', 3, current_date, 'Active');

insert into company (id, company_name, created_on, created_by, country_id)
values(2, 'LB', current_date, 1, (select id from country where country_name = 'India'));

ALTER TABLE users ENABLE TRIGGER ALL;
-- end of inserts only for unit tests


delete from master_data;
INSERT INTO MASTER_DATA (TYPE, VALUE)
VALUES
 ('education', 'Association of Chartered Certifed Accountants (ACCA)'),
 ('education', 'Bachelor of Arts (BA)'),
 ('education', 'Bachelors of Ayurveda Medicine & Surgery (BAMS)'),
 ('education', 'Bachelor of Architecture (BArch)'),
 ('education', 'Bachelor of Business Administration (BBA)'),
 ('education', 'Bachelor of Business Management (BBM)'),
 ('education', 'Bachelors of Business Studies (BBS)'),
 ('education', 'Bachelor of Computer Applications (BCA)'),
 ('education', 'Bachelor of Commerce in Computer Application (BCCA)'),
 ('education', 'Business Capacity Management (BCM)'),
 ('education', 'Bachelor of Commerce (BCom)'),
 ('education', 'Bachelor of Computer Science (BCS)'),
 ('education', 'Bachelor of Design (BDes)'),
 ('education', 'Bachelor of Dental Science (BDS)'),
 ('education', 'Bachelor of Engineering (BE)'),
 ('education', 'Bachelor of Education (BEd)'),
 ('education', 'Bachelor in Fine Arts (BFA)'),
 ('education', 'Bachelor in Foreign Trade (BFT)'),
 ('education', 'Bachelor of Hotel Management (BHM)'),
 ('education', 'Bachelor of Homeopathic Medicine and Surgery (BHMS)'),
 ('education', 'Bachelor of Information Technology (BIT)'),
 ('education', 'Bachelor of Marketing Management (BMM)'),
 ('education', 'Bachelor in Management Studies (BMS)'),
 ('education', 'Bachelor of Pharmacy (BPharma)'),
 ('education', 'Bachelor of Law (LLB)'),
 ('education', 'Bachelor in Medicine and Bachelor of Surgery (MBBS)'),
 ('education', 'Bachelor of Science (BSc)'),
 ('education', 'Bachelor of  Science in Software Engineering (BSSE)'),
 ('education', 'Bachelor of Technology. (BTech)'),
 ('education', 'Bachelor of Veterinary Science (BVSc)'),
 ('education', 'Chartered Accountant (CA)'),
 ('education', 'Chartered Aaccountant Integrated Professional Competence Course (CA IPCC)'),
 ('education', 'Chartered Financial Accountant  (CFA)'),
 ('education', 'Commercial Art(Commercial Art)'),
 ('education', 'Company Secretary (CS)'),
 ('education', 'Cost and Works Accountancy (CWA)'),
 ('education', 'Diploma (Diploma)'),
 ('education', 'Diploma in Graphics & Animation (Diploma in Graphics & Animation)'),
 ('education', 'Doctor Of Philosophy (PhD)' ),
 ('education', 'Executive Post Graduate Diploma in Business Management (EMBA)'),
 ('education', 'Fashion/Designing (Fashion/Designing)'),
 ('education', 'Fellow of Chartered Accountants (FCA)'),
 ('education', 'Graduate Diploma in Arts (GD Arts)'),
 ('education', 'Graduate Diploma in Business Administration (GDBA)'),
 ('education', 'Higher Secondary School Certificate (HSC)'),
 ('education', 'Integrated PG Course (I PG Course)'),
 ('education', 'Institute of Cost Accountants of India - Cost and Management Accountant (ICAI CMA)'),
 ('education', 'Institute of Cost and Works Accountant of India (ICWA)'),
 ('education', 'Journalism/Mass Comunication (Journalism/Mass Comm.)'),
 ('education', 'Masters in Information Management (MIM)'),
 ('education', 'Master of Law (LLM)'),
 ('education', 'Master of Arts (MA)'),
 ('education', 'Master of Architecture (MArch)'),
 ('education', 'Master of Business Administration (MBA)'),
 ('education', 'Master of Business Management (MBM)'),
 ('education', 'Master of Computer Applications (MCA)'),
 ('education', 'Master of Computer Management (MCM)'),
 ('education', 'Master of Commerce (MCom)'),
 ('education', 'Masters in Diploma in Business Administration (MDBA)'),
 ('education', 'Management Development Programmes (MDP)'),
 ('education', 'Masters of Engineering (ME)'),
 ('education', 'Master of Education (MEd)'),
 ('education', 'Mechanical, Electrical and Plumbing (MEP)'),
 ('education', 'Masters in Fine Arts (MFA)'),
 ('education', 'Masters of finance and control (MFC)'),
 ('education', 'Master of Financial Management (MFM)'),
 ('education', 'Masters in Management Studies (MMS)'),
 ('education', 'Master of Pharmacy (MPharma)'),
 ('education', 'Masters of Philosophy (MPhil)'),
 ('education', 'Master of Personnel Management (MPM)'),
 ('education', 'Masters of Science (MS)'),
 ('education', 'Master of Science in Computer Science (MS CS)'),
 ('education', 'Master of Computer Science (MCS)'),
 ('education', 'Masters in Industrial Psychology (MS in Industrial Psychology)'),
 ('education', 'Masters of Surgery / Doctor of Medicine (MS/MD)'),
 ('education', 'Master of Science (MSc)'),
 ('education', 'Master of Social Work (MSW)'),
 ('education', 'Master of Technology (MTech)'),
 ('education', 'Master of Veterinary Science (MVSc)'),
 ('education', 'Post Graduate Diploma (PG Diploma)'),
 ('education', 'Post Graduate Certification in Business Management (PGCBM)'),
 ('education', 'Postgraduate Certificate in Human Resource Management (PGCHRM)'),
 ('education', 'Post Graduate Diploma in Analytical Chemistry (PGDAC)'),
 ('education', 'Post Graduate Diploma in Business Administration (PGDBA)'),
 ('education', 'Post Graduate Diploma in Computer Application (PGDCA)'),
 ('education', 'Post Graduate Degree in Management (PGDM)'),
 ('education', 'Post Graduate Programme in Management (PGM)'),
 ('education', 'Post Graduate Program (PGP)'),
 ('education', 'Post Graduate Programme in Business Management (PGPBM)'),
 ('education', 'Public Relations / Advertising (PR/Advertising)'),
 ('education', 'Tourism (Tourism)'),
 ('education', 'Vocational-Training (Vocational Training)'),
 ('education', 'Other (Other)'),

 ( 'questionType','Checkbox'),
 ( 'questionType','Radio button'),
 ( 'questionType','InputBox'),
 ( 'questionType','Location'),
 ( 'questionType','Slider'),
 ( 'questionType','Calendar'),

 ( 'addressType','Job Location'),
 ( 'addressType','Interview Location'),
 ( 'addressType','Both'),

 ( 'process','Hiring Manager'),
 ( 'process','Lead Recruiter'),
 ( 'process','Sourcing'),
 ( 'process','Screening'),
 ( 'process','Interview'),
 ( 'process','Offer Management'),

 ( 'noticePeriod','0'),
 ( 'noticePeriod','15'),
 ( 'noticePeriod','30'),
 ( 'noticePeriod','60'),
 ( 'noticePeriod','45'),
 ( 'noticePeriod','90'),
 ( 'noticePeriod','Others');


delete from configuration_settings;
-- max limits for various parameters
insert into CONFIGURATION_SETTINGS(CONFIG_NAME, CONFIG_VALUE) values
('maxScreeningQuestionsLimit',50),
('dailyCandidateUploadPerUserLimit',500),
('dailyCandidateInviteLimit',500),
('candidatesPerFileLimit',100),
('sendEmail',1),
('sendSms',1),
('maxCvFiles',20),
('mlCall',1),
('maxCapabilities',10),
('cvRatingTimeout', 5000),
('otpExpiryMinutes', 3);


delete from skills_master;
 -- key skill master data
insert into skills_master (skill_name) values
('Core Java'),
('Advance Java'),
('J2EE'),
('Spring'),
('Hibernate'),
('Struts'),
('Swing'),
('MultiThreading'),
('Java Beans'),
('JSF'),
('JSP'),
('JDBC'),
('JMS'),
('Servlets'),
('Collections'),
('WebServices - Soap'),
('WebServices - Rest'),
('EJB'),
('Play'),
('JavaFX'),
('Netty'),
('Wicket'),
('JMX'),
('JAF'),
('JPA'),
('Ant'),
('Maven'),
('Gradle'),
('Tomcat'),
('JBoss'),
('GlassFish'),
('WebLogic'),
('TestNG'),
('Cactus'),
('EasyMock'),
('Mockito'),
('Cucumber'),
('Javascript - AngularJS'),
('Javascript - NodeJS'),
('Javascript - ExtJS'),
('Javascript - BackboneJS'),
('Javascript - DOJO'),
('Javascript - Jquery'),
('Javascript - EmberJS'),
('Javascript - ReactJS'),
('Javascript - KnockoutJS'),
('HTML'),
('HTML 5'),
('CSS'),
('Photoshop'),
('UX Designer'),
('CorelDraw'),
('Silverlight'),
('AJAX'),
('Javascript - Sails'),
('Javascript - Express'),
('Javascript - Grunt/Gulp'),
('Javascript - Brocolli'),
('Javascript - Webpack'),
('Javascript - Jasmine'),
('Javascript - Karma'),
('Javascript - Mocha'),
('.Net '),
('.Net - C#.Net'),
('.Net - VB.Net'),
('WCF'),
('WPF'),
('TFS'),
('VB'),
('MVC'),
('ADO'),
('Azure'),
('C#'),
('Sharepoint'),
('Excel'),
('TSQL'),
('SQL Server'),
('SQL Server SSRS'),
('SQL Server SSAS'),
('SQL Server SSIS'),
('TFS'),
('ASP'),
('Exchange'),
('ASP.NET Web API (2)'),
('ASP.NET MVC'),
('ASP.NET Web Forms (old school)'),
('nHibernate'),
('Entity Framework'),
('Linq2SQL'),
('ADO.NET'),
('nUnit'),
('SpecFlow'),
('MStest'),
('VC++'),
('STL'),
('Boost'),
('QT'),
('vxWidgets'),
('Loki'),
('POCO'),
('OpenCV'),
('VC'),
('Big Data - HBase'),
('Big Data - Hadoop'),
('Big Data - Hive'),
('Big Data - Spark'),
('Big Data - MapReduce'),
('Big Data - HDFS'),
('Big Data - MongoDB'),
('Oracle'),
('Oracle - BAM'),
('Oracle - Financials'),
('Oracle - Middleware'),
('Oracle - ORMB'),
('Oracle - SQL'),
('Oracle - Essbase'),
('MySQL'),
('NoSQL'),
('NoSQL - Cassandra'),
('NoSQL - MongoDB'),
('NoSQL - Berkeley DB'),
('NoSQL - Redis'),
('NoSQL - Riak'),
('NoSQL - CouchDB'),
('NoSQL - DynamoDB'),
('MySQL Stored Procedures'),
('MSSQL'),
('SQL'),
('DB2'),
('Postgresql'),
('Sybase'),
('Architecture'),
('Access'),
('SQLite'),
('Windows'),
('Linux'),
('RedHat RHEL'),
('Solaris'),
('Unix'),
('Android'),
('Mac/iOS'),
('Manual'),
('UAT'),
('Automation - Selenium'),
('Automation - Required'),
('Automation - Jasmine'),
('Automation - JUnit'),
('Automation - Protactor'),
('Automation - Silk Test'),
('Automation - Sahi Pro'),
('Automation - WebDriver'),
('Automation - SoapUI'),
('Automation - Watir'),
('Automation - Watin'),
('Automation - QTP'),
('Automation - Cucumber'),
('Automation - IBM Rational Functional Tester'),
('Automation - Appium'),
('Validation and Verification'),
('Performance - JMeter'),
('Performance - HP QC'),
('Performance - NeoLoad'),
('Performance - LoadRunner'),
('Performance - LoadUI'),
('Performance - Siege'),
('Performance - Gatling'),
('Infrastructure - SFTP'),
('Infrastructure - Vmware'),
('Infrastructure - SCCM'),
('Infrastructure - SCOM'),
('Infrastructure - Websence'),
('Infrastructure - Active Directory'),
('Infrastructure - Xendesktop'),
('Infrastructure - Netscalar'),
('Infrastructure - DNS'),
('Infrastructure - Web DMZ'),
('Infrastructure - ITIL'),
('Infrastructure - Application Packaging'),
('Application - JSB'),
('Application - Siebel'),
('Production'),
('Reporting - Regulatory Reporting'),
('Financial Planning and Analysis'),
('Trade Finance - Collateral Management'),
('Trade Finance'),
('Trade Finance - Settlement'),
('Risk - Market Risk'),
('Risk - Credit Risk'),
('CA'),
('Accounting'),
('PMO'),
('Fund Acounting'),
('Fund Acounting'),
('Internal Audit'),
('Finance Audit'),
('IT Audit'),
('NGO Audit'),
('HR'),
('ETL'),
('Informatica'),
('Pentaho'),
('Cognos'),
('Abinitio'),
('Business Objects'),
('Chef'),
('Puppet'),
('SVN'),
('Ansible'),
('Jenkins'),
('Artifactory'),
('Integration - Continuous'),
('Integration - Tools'),
('Nexus'),
('KVM'),
('Xen'),
('Xen'),
('VirtualBox'),
('Vagrant'),
('CFEngine'),
('SaltStack'),
('RANCID'),
('Ubuntu Juju'),
('RANCID'),
('New Relic'),
('Nagios'),
('Icinga'),
('Graphite'),
('Ganglia'),
('Cacti'),
('PagerDuty'),
('Sensu'),
('TCP/IP'),
('HTTP'),
('HTTP/2'),
('WebSockets'),
('Web Servers - Apache'),
('Web Servers - Tomcat'),
('Web Servers - IIS'),
('Web Servers - jBoss'),
('Scrum Master'),
('PMO'),
('PM'),
('Technical'),
('Business Analysis'),
('Perl'),
('Shell'),
('Python'),
('Ruby'),
('Bash'),
('AWK'),
('Python'),
('Ruby'),
('Lua'),
('Sinatra'),
('Padrino'),
('JRuby'),
('RSpec'),
('Capybara'),
('Watir'),
('Cucumber'),
('Passenger'),
('Capistrano'),
('Cake PHP'),
('Lucene'),
('Codeignitor'),
('Wordpress'),
('Joomla'),
('Symfony (2)'),
('Zend Framework (2)'),
('Yii'),
('Laravel'),
('Twig (templating)'),
('PHPUnit (testing)'),
('Doctrine (ORM)'),
('PHPStorm (IDE)'),
('Pear'),
('Smarty'),
('FICO'),
('ABAP'),
('HANA'),
('ME/MII'),
('Security'),
('MM'),
('SAP - Basis'),
('SAP - SCM'),
('GIT'),
('Subversion'),
('Endevor'),
('Mercurial'),
('SVN'),
('CVS'),
('Perforce'),
('Bitbucket'),
('Gitlab'),
('Goldensource'),
('Illustrator'),
('Flex'),
('CS'),
('Jasper/iReport'),
('Jira'),
('Pega'),
('TIBCO'),
('Tivoli'),
('Tableau'),
('TeamCity'),
('Murex'),
('Apache Kafka'),
('Memcached'),
('Nginx'),
('Varnish'),
('Squid'),
('haproxy'),
('CDN'),
('Big Data - Pig'),
('Big Data - Apache HBase'),
('Big Data - Cassandra'),
('Big Data - MapReduce'),
('Big Data - Spark'),
('TFS'),
('CruiseControl'),
('Bamboo'),
('Hudson'),
('Travis'),
('Mantis'),
('Confluence'),
('RedMine'),
('YouTrack'),
('Trello'),
('BaseCamp'),
('Visual Studio'),
('Eclipse'),
('NetBeans'),
('Aptana'),
('xCode'),
('WebStorm'),
('IntelliJ IDEA'),
('LAMP'),
('MVC'),
('OOPs'),
('SaaS'),
('Text NLP'),
('Ruby On Rails'),
('Swift'),
('XML'),
('JSON'),
('Scala'),
('Erlang'),
('OCaml'),
('Haskell'),
('F#'),
('Clojure'),
('Elixir'),
('Joomla'),
('Drupal'),
('Wordpress'),
('Magento (for e-commerce)'),
('Django'),
('Flask'),
('Pyramid'),
('Pylons'),
('SQLAlchemy'),
('web2py'),
('Kivy'),
('Akka'),
('Cats'),
('Lift'),
('Play'),
('Scalaz'),
('Slick'),
('Shapeless'),
('Spray'),
('iOS - Objective C'),
('iOS - Swift'),
('iOS - CoreData'),
('iOS - Cocoa'),
('iOS - Cocoa Touch'),
('iOS - UIKit'),
('iOS - CoreLocation'),
('iOS - CoreFoundation'),
('iOS - CoreImage'),
('iOS - CoreGraphics'),
('iOS - Cocoa Pods'),
('iOS - Flurry'),
('iOS - TestFlight'),
('iOS - HockeyApp'),
('Android - SDK'),
('Android - NDK'),
('Android - IDE'),
('Android - Gradle'),
('Android - AndEngine'),
('Android - Robotium'),
('jQuery Mobile'),
('PhoneGap'),
('Sencha Touch'),
('Dojo Mobile'),
('Titanium'),
('Xamarin'),
('OOD'),
('Design Patterns'),
('MVC'),
('SOA'),
('UML'),
('Webservices'),
('Markup'),
('Markup - XML'),
('Markup - XSLT'),
('Markup - xPath'),
('Markup - XMPP'),
('API'),
('API - Facebook API'),
('API - Google API'),
('API - Twitter API'),
('Agile'),
('Accounts Payable'),
('Asset Management'),
('Automation - Appium'),
('Business Intelligence'),
('Bootstrap'),
('C++'),
('C'),
('Chatbot'),
('CICS'),
('Citrix'),
('Claims'),
('Cloud Computing'),
('COBOL'),
('Data Analysis'),
('Data Mining'),
('Data Modelling'),
('Data Science'),
('Digital'),
('ERP/CRM'),
('Firewall'),
('Firewall'),
('Forecasting'),
('Fund Management'),
('GoldenGate'),
('Grails'),
('Hyperion'),
('Indirect Taxation'),
('Internet Protocol'),
('Marketing'),
('Digital'),
('Marketing-Head'),
('Maximo'),
('MDM'),
('Microservices'),
('MicrosoftExchange'),
('MongoDB'),
('NAT'),
('Neoload'),
('Neoload'),
('Security'),
('Networking'),
('OBIEE'),
('OFSAA'),
('OIPA'),
('OMNI'),
('Oozie'),
('OracleFusion'),
('ORMB'),
('Peoplesoft'),
('PHP'),
('QTP'),
('Recruitment'),
('Regulatory Reporting'),
('Requirement Gathering'),
('Risk'),
('Robotic Procees Automation'),
('Sailpoint'),
('Salesforce'),
('SAN'),
('SAP'),
('SAP - ICM'),
('SAP - R3'),
('SAS'),
('SCCM'),
('Big Data - Sqoop'),
('Big Data - Sqoop'),
('ServiceDesk'),
('ServiceNow'),
('Statutory Audit'),
('Tally'),
('Technical Writer'),
('UI Designer'),
('VPN'),
('Web Servers - WebLogic'),
('WindowsFAX'),
('FreeSwitch');

delete from sms_templates;
INSERT INTO SMS_TEMPLATES (TEMPLATE_NAME, TEMPLATE_CONTENT) VALUES
('ChatInvite','NEW JOB ALERT - [[${commBean.receiverfirstname}]], your profile is shortlisted by [[${commBean.sendercompany}]] for [[${commBean.jobtitle}]]. Click [[${commBean.chatlink}]] to see JD and apply.'),
('ChatCompleted','Congratulations [[${commBean.receiverfirstname}]]! Your application is complete for the [[${commBean.jobtitle}]] position at [[${commBean.sendercompany}]]. We will be in touch with you soon.'),
('ChatIncompleteReminder1','Your application to [[${commBean.sendercompany}]] was incomplete. Just click the [[${commBean.chatlink}]] to continue and complete.'),
('ChatIncompleteReminder2','FINAL REMINDER - Complete your application for [[${commBean.jobtitle}]] job at [[${commBean.sendercompany}]]. It will take only 5 minutes. Click [[${commBean.chatlink}]] to continue.'),
('LinkNotVisitedReminder1','[[${commBean.receiverfirstname}]], [[${commBean.sendercompany}]] has shortlisted you for [[${commBean.jobtitle}]] Job. Click [[${commBean.chatlink}]] to know more and apply.'),
('LinkNotVisitedReminder2','Not interested in this job? [[${commBean.sendercompany}]] has invited you to apply for the [[${commBean.jobtitle}]] position. Click [[${commBean.chatlink}]] to start.'),
('ChatNotVisitedReminder1','[[${commBean.receiverfirstname}]], this is link to apply for [[${commBean.jobtitle}]] job at [[${commBean.sendercompany}]]. It is valid only for 24 hours. Click [[${commBean.chatlink}]] to begin.'),
('ChatNotVisitedReminder2','[[${commBean.receiverfirstname}]], Just a reminder to complete your application for [[${commBean.jobtitle}]] job at [[${commBean.sendercompany}]]. This link will expire in 24 hours. [[${commBean.chatlink}]] '),
('AutosourceAcknowledgement', 'Hi [[${commBean.receiverfirstname}]], Your application for [[${commBean.jobtitle}]] position at [[${commBean.sendercompany}]] has been received. Good luck!'),
('AutosourceApplicationShortlisted', '[[${commBean.receiverfirstname}]], [[${commBean.sendercompany}]] has shortlisted you for [[${commBean.jobtitle}]] position. Click on link to complete your profile. [[${commBean.chatlink}]] '),
('AutosourceLinkNotVisited', 'Last Reminder [[${commBean.receiverfirstname}]] - [[${commBean.sendercompany}]] has shortlisted your application. Click link to complete your profile. [[${commBean.chatlink}]]'),
('OTPSms','Your OTP for [[${commBean.sendercompany}]] job application is [[${commBean.otp}]]. This OTP will expire in [[${commBean.otpExpiry}]] minutes.'),
('InterviewDay', 'INTERVIEW REMINDER FOR [[${commBean.receiverfirstname}]] - You have an interview with [[${commBean.sendercompany}]] today at [[${commBean.interviewdate}]]. Please report 15 mins before. Click Google Maps link for directions. See you there! [[${commBean.interviewAddressLink}]]');

delete from create_job_page_sequence;
INSERT INTO CREATE_JOB_PAGE_SEQUENCE (PAGE_DISPLAY_NAME, PAGE_NAME, PAGE_DISPLAY_ORDER, DISPLAY_FLAG,SUBSCRIPTION_AVAILABILITY)
VALUES
('Overview', 'overview', 1, 'T','Lite'),
('Expertise', 'expertise', 3, 'F','Lite'),
('Job Detail', 'jobDetail', 8, 'F','Max'),
('Screening', 'screeningQuestions', 2, 'T','Lite'),
('Key Skills', 'keySkills', 4, 'T','Lite'),
('Hiring Team', 'hiringTeam', 6, 'T','Max'),
('Capabilities', 'capabilities', 5, 'T','Lite'),
('Preview', 'preview', 7, 'T','Lite');

INSERT INTO MASTER_DATA (TYPE, VALUE, VALUE_TO_USE, COMMENTS)
VALUES
 ( 'expertise','Beginner', 1, 'Candidate has 1-2 years of relevant work experience and works on given tasks on day to day basis. Exposure to job complexities is limited and needs support/guidance for complex tasks.'),
 ( 'expertise','Competent', 2, 'Candidate can independently handle all tasks. Typically has 2 - 5 years of relevant work experience. Dependable on senior for assigned work. Can participate in training/grooming of juniors'),
 ( 'expertise','Expert', 3, 'Considered as a Master in the organization/industry. Candidate can handle highly complex scenarios and is the go-to person for others. Such candidates are rare to find and often come at a high cost. Select this option if you want to hire a expert.');

INSERT INTO MASTER_DATA (TYPE, VALUE)
VALUES
( 'experienceRange', '0 - 2 Years'),
( 'experienceRange', '2 - 4 Years'),
( 'experienceRange', '4 - 6 Years'),
( 'experienceRange', '6 - 8 Years'),
( 'experienceRange', '8 - 10 Years'),
( 'experienceRange', '10 - 15 Years'),
( 'experienceRange', '15 - 20 Years'),
( 'experienceRange', '20+ Years'),

( 'function','Accounting / Tax / Company Secretary / Audit'),
( 'function','Agent'),
( 'function','Airline / Reservations / Ticketing / Travel'),
( 'function','Analytics & Business Intelligence'),
( 'function','Anchoring / TV / Films / Production'),
( 'function','Architects / Interior Design / Naval Arch');

delete from weightage_cutoff_mapping;
insert into weightage_cutoff_mapping (weightage, percentage, cutoff, star_rating)
values
(2,100,10,1),
(2,100,20,2),
(2,80,40,3),
(2,40,80,4),
(2,20,100,5),
(6,100,20,1),
(6,100,40,2),
(6,60,60,3),
(6,20,100,4),
(6,0,100,5),
(10,0,30,1),
(10,0,50,2),
(10,0,70,3),
(10,0,80,4),
(10,0,100,5);

INSERT INTO public.currency(currency_full_name, currency_short_name, country) VALUES
('Australian Dollar', 'AUD', 'au'),
('Canadian Dollar', 'CAD', 'ca'),
('Indian Rupee', 'INR', 'in'),
('Singapore Dollar', 'SGD', 'sg'),
('Pound Sterling', 'GBP', 'gb'),
('US Dollar', 'USD', 'us');

Insert into STAGE_STEP_MASTER(STAGE, STEP)
VALUES ('Sourcing','Sourcing'),
('Screening','Screening'),
('Submitted','Submitted'),
('Interview','L1'),
('Make Offer','Make Offer'),
('Offer','Offer'),
('Hired','Hired');

INSERT INTO public.master_data(type, value, value_to_use) VALUES
('role', 'HR Recruiter', 'Recruiter'),
('role', 'HR Head', 'ClientAdmin'),
('role', 'Admin', 'ClientAdmin'),
('role', 'Hiring Manager', 'BusinessUser'),
('role', 'Interviewer', 'BusinessUser');

--Ticket #258
INSERT INTO export_format_master
(format, system_supported)
values
('All Data', true);

INSERT INTO export_format_detail
(format_id, column_name, header,  "position", stage)
VALUES
(1, 'candidateName','Candidate Name', 1, null),
(1, 'chatbotStatus','Chatbot Status', 2, null),
(1, 'chatbotFilledTimeStamp', 'Chatbot Filled Timestamp', 3, null),
(1, 'currentStage','Stage', 4, null),
(1, 'keySkillsStrength','Key Skills Strength', 5, null),
(1, 'currentCompany','Current Company', 6, null),
(1, 'currentDesignation','Current Designation', 7, null),
(1, 'email','Email', 8, null),
(1, 'countryCode','Country Code', 9, null),
(1, 'mobile','Mobile', 10, null),
(1, 'totalExperience','Total Experience', 11, null),
(1, 'createdBy','Created By', 12, null),
(1, 'interviewDate','Interview Date', 13, 'Interview'),
(1, 'interviewType','Interview Type', 14, 'Interview'),
(1, 'interviewMode','Interview Mode', 15, 'Interview'),
(1, 'interviewLocation','Interview location', 16, 'Interview'),
(1, 'candidateConfirmation','Candidate Confirmation', 17, 'Interview'),
(1, 'candidateConfirmationTime','Candidate Confirmation Time', 18, 'Interview'),
(1, 'showNoShow','Show No Show', 19, 'Interview'),
(1, 'noShowReason','No Show Reason' ,20, 'Interview'),
(1, 'cancelled', 'Interview Cancelled', 21, 'Interview'),
(1, 'cancellationReason','Cancellation Reason', 22, 'Interview');

Insert into MASTER_DATA (TYPE, VALUE) values
('reasonForChange','Too much time spent in Commuting to work'),
('reasonForChange','Too much travelling in the job'),
('reasonForChange','Have been in same company for too long'),
('reasonForChange','Company has shutdown'),
('reasonForChange','Company is downsizing /got a layoff'),
('reasonForChange','Am a Contract employee, want to shift to permanent employment'),
('reasonForChange','Want to work in a different domain'),
('reasonForChange','Want to work in a different project'),
('reasonForChange','Not getting paid my salary on time'),
('reasonForChange','Have not been promoted for a long time'),
('reasonForChange','Want to work with a Larger Size Company'),
('reasonForChange','Want to work with a Bigger Brand'),
('reasonForChange','Want to get away from shift working'),
('reasonForChange','Have been on maternity break'),
('reasonForChange','Have been on Sabbatical'),
('reasonForChange','Other');

INSERT INTO MASTER_DATA(TYPE, VALUE) VALUES
('callOutCome', 'Connected'),
('callOutCome', 'No Answer'),
('callOutCome', 'Busy'),
('callOutCome', 'Wrong Number'),
('callOutCome', 'Left Message/VoiceMail');

Insert into MASTER_DATA (TYPE, VALUE) values
('cancellationReasons','Client cancelled iv 1'),
('cancellationReasons','Candidate no show 1'),
('cancellationReasons','Panel not available 1'),
('cancellationReasons','Client cancelled iv 2'),
('cancellationReasons','Candidate no show 2'),
('cancellationReasons','Panel not available 2'),

('noShowReasons','Personal/Family'),
('noShowReasons','Professional'),
('noShowReasons','Medical'),
('noShowReasons','Logistics'),
('noShowReasons','Not reachable'),
('noShowReasons','Client Cancellation');

INSERT INTO CV_PARSING_API_DETAILS (API_URL, API_SEQUENCE, ACTIVE, COLUMN_TO_UPDATE, QUERY_ATTRIBUTES) VALUES
('https://rest.rchilli.com/RChilliParser/Rchilli/parseResume', 1, false, 'PARSING_RESPONSE_JSON',
'"userkey" => "2SNEDYNPV30",
"version" => "7.0.0",
"subuserid" => "Hexagon Search"'
),
('http://cvparser.litmusblox.net/parsecv', 2, true, 'PARSING_RESPONSE_PYTHON',null
),
('https://cia1z4r0d4.execute-api.ap-south-1.amazonaws.com/Test/resumeParser-Test', 3, true, 'PARSING_RESPONSE_ML',
null
);

INSERT INTO REJECTION_REASON_MASTER_DATA (VALUE, LABEL, TYPE, STAGE) VALUES
('Company', '','Candidate Reasons', 1),
('Shift', 'Candidate does not want to work in shifts','Candidate Reasons', 1),
('Commute', 'Candidate not willing to commute','Candidate Reasons', 1),
('IC Role', 'Candidate not willing to work in Individual Contributor (IC) role','Candidate Reasons', 1),
('People Role', 'Candidate not willing to work in People Management role','Candidate Reasons', 1),

('Company', '','Candidate Reasons', 2),
('Shift', 'Candidate does not want to work in shifts','Candidate Reasons', 2),
('Commute', 'Candidate not willing to commute','Candidate Reasons', 2),
('IC Role', 'Candidate not willing to work in Individual Contributor (IC) role','Candidate Reasons', 2),
('People Role', 'Candidate not willing to work in People Management role','Candidate Reasons', 2),

('Job Hops', 'Candidate has many job changes','Recruiter Reasons', 1),
('Over Budget', 'Candidates salary expectation is higher than budget','Recruiter Reasons', 1),
('No Poach', 'Candidate works in No Poach company','Recruiter Reasons', 1),
('Skill Missing', 'Candidate is missing required skills','Recruiter Reasons', 1),
('Already interviewed', 'Candidate has given interview earlier','Recruiter Reasons', 1),
('Over-Qualified', 'Candidate has more experience than required','Recruiter Reasons', 1),
('Under-Qualified', 'Candidate has less experience than required','Recruiter Reasons', 1),
('Education', 'Candidate does not have the correct education qualifications','Recruiter Reasons', 1),
('Communication', 'Candidate does not have adequate communication skills','Recruiter Reasons', 1),
('Notice Period', 'Candidates Notice Period is too long','Recruiter Reasons', 1),
('Not Available', 'Candidate not available for interview on a specific date','Recruiter Reasons', 1),
('Not interested', 'Candidate not interested in this job','Recruiter Reasons', 1),
('Not looking', 'Candidate is not looking for a job change','Recruiter Reasons', 1),
('Key Skill Strength', 'Candidate Key Skill Strength is poor','Recruiter Reasons', 1),
('No Response', 'Candidate has not responded to chatbot invitation','Recruiter Reasons', 1),
('Chatbot Incomplete', 'Candidate has not completed the chatbot','Recruiter Reasons', 1),
('Not Interested', 'Candidate has expressed disinterest in the job','Recruiter Reasons', 1),

('Job Hops', 'Candidate has many job changes','Recruiter Reasons', 2),
('Over Budget', 'Candidates salary expectation is higher than budget','Recruiter Reasons', 2),
('No Poach', 'Candidate works in No Poach company','Recruiter Reasons', 2),
('Skill Missing', 'Candidate is missing required skills','Recruiter Reasons', 2),
('Already interviewed', 'Candidate has given interview earlier','Recruiter Reasons', 2),
('Over-Qualified', 'Candidate has more experience than required','Recruiter Reasons', 2),
('Under-Qualified', 'Candidate has less experience than required','Recruiter Reasons', 2),
('Education', 'Candidate does not have the correct education qualifications','Recruiter Reasons', 2),
('Communication', 'Candidate does not have adequate communication skills','Recruiter Reasons', 2),
('Notice Period', 'Candidates Notice Period is too long','Recruiter Reasons', 2),
('Not Available', 'Candidate not available for interview on a specific date','Recruiter Reasons', 2),
('Not interested', 'Candidate not interested in this job','Recruiter Reasons', 2),
('Not looking', 'Candidate is not looking for a job change','Recruiter Reasons', 2),
('Key Skill Strength', 'Candidate Key Skill Strength is poor','Recruiter Reasons', 2),
('No Response', 'Candidate has not responded to chatbot invitation','Recruiter Reasons', 2),
('Chatbot Incomplete', 'Candidate has not completed the chatbot','Recruiter Reasons', 2),
('Not Interested', 'Candidate has expressed disinterest in the job','Recruiter Reasons', 2),

('Skill Missing', 'Candidate is missing required skills',null, 3),
('Industry / Domain', 'Candidate is missing Industry / Domain background',null, 3),
('Already interviewed', 'Candidate has been interviewed earlier',null, 3),
('Over-Qualified', 'Candidate has more experience than required',null, 3),
('Under-Qualified', 'Candidate has less experience than required',null, 3),
('Education', 'Candidate does not have the required education qualifications',null, 3),
('Communication', 'Candidate does not have adequate communication skills',null, 3),
('Assessment', 'Candidate did not clear the assessment test',null, 3),

('Technical', 'Technical skills not adequate',null, 4),
('Managerial', 'Managerial / People skills not adequate',null, 4),
('Culture', 'Not a culture fit for the company',null, 4),
('Industry / Domain', 'Industry / Domain experience not adequate',null, 4),
('Behavioral', 'Behavioral competencies not adequate',null, 4),
('Compensation fitment', 'Not able to fit candidate in the compensation band',null, 4),
('Another Candidate', 'Another candidate selected for this job',null, 4),

('Personal/Family', 'Personal or Family emergency',null, 4),
('Professional', 'Unexpected meeting, Client visit, Production issue',null, 4),
('Medical', 'Medical Emergency, Candidate unwell',null, 4),
('Logistics', 'Weather / Accident / Vehicle problems',null, 4),
('No Response', 'Candidate has stopped responding to calls',null, 4),
('Hiring Manager', 'Hiring Manager cancelled / rescheduled the interview',null, 4),

('Position Scrapped', 'Position has been scrapped',null, 5),
('No Approval', 'No approval for position / Approval withdrawn',null, 5),
('Other Offer', 'Candidate received another offer',null, 5),
('Withdraw Candidature', 'Candidate is no longer interested in the job',null, 5),

('Role', 'Candidate did not like the Role offered',null, 6),
('Title', 'Candidate did not like the Title offered',null, 6),
('Compensation', 'Candidate did not like to Compensation offered',null, 6),
('Interview experience', 'Candidate did not like the Interview expereince',null, 6),
('Relocation', 'Candidate does not want to Relocate',null, 6),
('Counteroffer', 'Candidate accepted counter-offer from his company',null, 6),
('Onsite', 'Candidate received an onsite opportunity',null, 6),
('Other Offer', 'Candidate accepted offer from another company',null, 6),
('Withdraw Offer', 'Company withdrew the offer',null, 6),

('Performance', 'Candidate was asked to leave on Performance grounds',null, 7),
('Background Verification', 'Candidates Background Verification (BGV) report was negative',null, 7),
('Integrity', 'Candidate was asked to leave on grounds of integrity',null, 7),
('Voluntary exit', 'Candidate left on their own accord',null, 7);