name: continuous integration and deployment job

on:
  push:
    branches:
      - development

jobs:
  BUILD_AND_DEPLOY_BACKEND_TEST:
    name: build and deploy backend test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.1
    - name: checkout to development and pull
      run: git checkout development; git pull origin development;
      shell: bash
    - name: Maven Package
      run: mvn -B clean package
